src/interfaces.ts
src/resend.ts

Add response types for `sendEmail()` covered the success and error scenarios

feat: add response types

---

examples/with-nextjs-typescript/package.json
examples/with-nextjs-typescript/yarn.lock

This PR fixes `examples/with-nextjs-typescript` by updating the package. All examples are now synced with the same `resend@0.8.0`.
Fixes #55

chore(examples): Upgrade `resend`

---

src/common/interfaces/get-option.interface.ts
src/common/interfaces/index.ts
src/common/interfaces/list-option.interface.ts
src/common/interfaces/post-option.interface.ts
src/common/interfaces/put-option.interface.ts
src/resend.ts

This PR adds some HTTP request methods helpers.

feat: Add request methods

---

src/interfaces.ts

Rather than just returning string/number these new types give developers a better idea of what errors the might receive. 
This setup was inspired by how TRPC types it's codes: https://github.com/trpc/trpc/blob/main/packages/server/src/rpc/codes.ts
I think it would be great and take this one step further by unifying the return types. There's no reason type, status, and message couldn't exist on the returned success value too.

feat: Map error response type

---

readme.md

This PR updates the README.md file to show usage of the new `emails.send` method, instead of the deprecated `sendEmail` method.

fix: Update readme.md to use new emails API

---

src/emails/interfaces/create-email-options.interface.ts

fix: Allow null in the type definition for CreateEmailOptions.react

---

src/emails/interfaces/create-email-options.interface.ts
src/resend.spec.ts

This PR updates the `CreateEmailOptions` type to ensure either `text` or `html` is set for the email payload to be valid.
This will ensure that either `CreateEmailWithHtmlOptions` or `CreateEmailWithTextOptions` is required. This change also allows both `html` & `text` to be used at the same time.
This PR also updates the tests to ensure that any mock tests without `html` or `text` contain either on of the fields.

fix: Ensure either `text` or `html` is a required field

---

src/emails/interfaces/create-email-options.interface.ts
src/resend.spec.ts

This PR adds JSDoc's for all types in the SDK. This allows the developer to quickly view information about a particular property without having to visit the documentation.

feat: Add JSdoc for create email types

---

package.json

This PR updates the organisation username from resend-inc to resendlabs. This is primarily for npm.com to use the correct repo links.

fix: package.json to use correct organization name

---

package.json
src/resend.ts
yarn.lock

The goal here is to help our SDK running in other runtimes, such as Deno. With this change the sdk can run just as fine in it.
Since Node v18 already has a global `fetch`, we don't need `node-fetch` for cross env compatibility.
Node v16 reached end of life and we don't need to support it anymore, let me me know if there could be any downsides of using the native fetch.
Instead of dropping `node-fetch` we could also try upgrading it to the latest version, which seems like it would work in Deno _but_ it's an ESM only package.

feat: Drop `node-fetch` in favor of native `fetch` for Node

---

src/resend.ts

fixes https://github.com/resend/resend-node/issues/237

fix: Undefined process

---

src/contacts/contacts.spec.ts
src/contacts/contacts.ts
src/contacts/interfaces/update-contact.interface.ts

This fixes the naming of the first name property in the update contact command to correctly reflect the documentation:
> **`firstName`** `string`
> The first name of the contact.

fix: Rename `fistName` to `firstName` typo

---

src/contacts/contacts.spec.ts
src/contacts/interfaces/update-contact.interface.ts

Updating the `UpdateContactResponseSuccess` interface to include the `object` property that was missing.

fix: Update contact response

---

src/contacts/interfaces/remove-contact.interface.ts
src/emails/interfaces/create-email-options.interface.ts

Updating Docs API-Reference URL to include /docs before /api-reference.
- https://resend.com/api-reference/emails/send-email#body-parameters
- https://resend.com/api-reference/emails/send-email#body-parameters
- https://resend.com/docs/api-reference/contacts/delete-contact#body-parameters
- https://resend.com/docs/api-reference/emails/send-email#body-parameters

chore: Update docs URL reference

---

src/domains/domains.spec.ts
src/domains/interfaces/verify-domain.interface.ts

Changing `VerifyDomainsResponseSuccess` to have only `object` and `id` properties like Resend docs
https://resend.com/docs/api-reference/domains/verify-domain

fix: Verify domain response

---

src/domains/domains.spec.ts
src/domains/interfaces/remove-domain.interface.ts

Including missing properties `object` and `deleted` to `RemoveDomainsResponseSuccess`
https://resend.com/docs/api-reference/domains/delete-domain

fix: Delete domain response

---

src/emails/emails.spec.ts
src/resend.ts

- do not throw when `fetch` itself fails due to being unable to resolve the connection
- throw better error message when the response is not a valid JSON
also closes #347

feat: Better treatment of errors from the API

---

package.json
pnpm-lock.yaml
src/batch/batch.ts
src/emails/emails.ts

use dynamic import for `@react-email/render` only when the `react` prop is used

feat: Use dynamic import for `@react-email/render`

---

src/broadcasts/broadcasts.spec.ts
src/broadcasts/broadcasts.ts
src/broadcasts/interfaces/broadcast.ts
src/broadcasts/interfaces/get-broadcast.interface.ts
src/broadcasts/interfaces/list-broadcasts.interface.ts
src/broadcasts/interfaces/remove-broadcast.interface.ts
src/emails/emails.spec.ts

This PR adds the ability to `get`, `remove`, and `list` broadcasts using the SDK.

feat: Add get, remove and list broadcast endpoints

---

package.json
src/batch/batch.ts
src/common/interfaces/email-api-options.interface.ts
src/common/utils/parse-email-to-api-options.spec.ts
src/common/utils/parse-email-to-api-options.ts
src/emails/emails.ts
src/emails/interfaces/create-email-options.interface.ts

Closes #421 
But it should reply to `delivered@resend.dev` instead.
Correctly mapping the Node.js SDK's fields to Resend's API so we do not forget any option in the payload.

fix: correct email batch api call with reply_to

---

package.json

We can confirm the fix is properly working by following [these instructions](https://github.com/joaopcm/resend-node-4.1.2-canary.0-demo).

release: bump version from 4.1.2-canary.0 to 4.1.2

---

src/contacts/contacts.spec.ts
src/contacts/contacts.ts
src/contacts/interfaces/get-contact.interface.ts

This PR adds support for retrieval of contacts by their email. We already had this for the [update method](https://arc.net/l/quote/mgcatgks) and the [delete](https://arc.net/l/quote/vnuqlvak). Only `get` was solely done with the ID option

feat: add support for retrieval of contact by email

---

package.json
src/common/interfaces/domain-api-options.interface.ts
src/common/utils/parse-domain-to-api-options.spec.ts
src/common/utils/parse-domain-to-api-options.ts
src/domains/domains.spec.ts
src/domains/domains.ts
src/domains/interfaces/create-domain-options.interface.ts

This PR adds support for sending a `customReturnPath` field to domains creation (`resend.domains.create`). It allows users to customize their SPF record host names.
The field is supposed to be optional and correctly parsed to snake case to match our API.

feat: add custom return path support for domains creation

---

src/batch/batch.spec.ts
src/batch/interfaces/create-batch-options.interface.ts

Similar to https://github.com/resend/resend-node/pull/489, adding support for idempotency keys on email batch sending.

feat: add idempotency key support to POST /emails/batch

---

src/contacts/contacts.ts
src/contacts/topics/contact-topics.spec.ts
src/contacts/topics/contact-topics.ts
src/contacts/topics/interfaces/get-contact-topics.interface.ts
src/contacts/topics/interfaces/update-contact-topics.interface.ts

This PR adds Contacts/Topics operations (`contacts.topics.patch` and `contacts.topics.get`) support to the SDK just as [described here](https://www.notion.so/resend/Unsubscribe-Topics-API-SDK-1ecc40d6c4ef80f29ee1c6b5c4038ccb)

feat: add contact topics endpoints to node sdk

---

src/contacts/contacts.spec.ts
src/contacts/contacts.ts
src/contacts/interfaces/get-contact.interface.ts
src/contacts/interfaces/remove-contact.interface.ts

Enables getting and removing global contacts by passing a string id or email as an alternative to using an object.
All of the followings are valid:
```ts
// Traditional object parameter
resend.contacts.get({email: "foo@bar.com"})
resend.contacts.get({id: "b6acc733-5320-4e28-bdcd-70e6006db885"})
// New string parameter
resend.contacts.get("foo@bar.com")
resend.contacts.get("b6acc733-5320-4e28-bdcd-70e6006db885")
```
Others:
- Added tests for string id/email and for cases where audienceId is omitted.

fix: global contacts friction log
